g++ js/src/jskwgen.cpp -o jsdbconfig1.exe
./jsdbconfig1.exe > js/jsautokw.h
g++ js/src/jscpucfg.cpp -o jsdbconfig2.exe
./jsdbconfig2.exe > js/jsautocfg.h
g++ js/src/jsoplengen.cpp -o jsdbconfig3.exe
./jsdbconfig3.exe js/jsautooplen.h
g++ jsdbconfigure.cpp -o jsdbconfig4.exe
./jsdbconfig4.exe > js/js-config.h
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;js/src/; js/; rs/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm jsdb.cpp -ojsdb.obj
brc32.exe -fo obj\jsdb.res jsdb.rc 
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_sqlite.cpp -owrap_sqlite.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_process.cpp -owrap_process.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_com.cpp -owrap_com.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_debug.cpp -owrap_debug.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_env.cpp -owrap_env.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_nums.cpp -owrap_nums.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_image.cpp -owrap_image.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_index.cpp -owrap_index.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_mail.cpp -owrap_mail.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_odbc.cpp -owrap_odbc.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_record.cpp -owrap_record.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_server.cpp -owrap_server.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_shell.cpp -owrap_shell.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_system.cpp -owrap_system.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_stream.cpp -owrap_stream.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_table.cpp -owrap_table.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/wrap_zip.cpp -owrap_zip.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/dbf_cache.cpp -odbf_cache.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/dbf_dat.cpp -odbf_dat.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/dbf_file.cpp -odbf_file.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/dbf_head.cpp -odbf_head.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/dbf_io.cpp -odbf_io.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/dbf_open.cpp -odbf_open.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/dbf_rec.cpp -odbf_rec.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/gif_font.cpp -ogif_font.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/gif_main.cpp -ogif_main.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/io_b64.cpp -oio_b64.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/io_comm.cpp -oio_comm.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/io_compress.cpp -oio_compress.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/io_expand.cpp -oio_expand.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/io_file.cpp -oio_file.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/io_inet.cpp -oio_inet.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/io_list.cpp -oio_list.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/io_memory.cpp -oio_memory.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/io_fifo.cpp -oio_fifo.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/io_open.cpp -oio_open.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/io_pipe.cpp -oio_pipe.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/io_print.cpp -oio_print.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/io_stream.cpp -oio_stream.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/io_xml.cpp -oio_xml.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/io_zip.cpp -oio_zip.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/ml_list.cpp -oml_list.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/ml_mapi.cpp -oml_mapi.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/ml_mapi2.cpp -oml_mapi2.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/ml_mime.cpp -oml_mime.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/ml_notes.cpp -oml_notes.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/ml_open.cpp -oml_open.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/ml_pop.cpp -oml_pop.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/ml_vim.cpp -oml_vim.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_alloc.cpp -osy_alloc.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_char.cpp -osy_char.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_crc.cpp -osy_crc.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_except.cpp -osy_except.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_file.cpp -osy_file.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_form.cpp -osy_form.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_int32.cpp -osy_int32.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_list.cpp -osy_list.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_mswin.cpp -osy_mswin.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_param.cpp -osy_param.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_sort.cpp -osy_sort.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_sql.cpp -osy_sql.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_string.cpp -osy_string.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_strlist.cpp -osy_strlist.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_time.cpp -osy_time.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_url.cpp -osy_url.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/sy_worm.cpp -osy_worm.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/tbl_asci.cpp -otbl_asci.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/tbl_cache.cpp -otbl_cache.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/tbl_data.cpp -otbl_data.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/tbl_dbf.cpp -otbl_dbf.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/tbl_index.cpp -otbl_index.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/tbl_main.cpp -otbl_main.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm rs/tbl_sql.cpp -otbl_sql.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm zlib/adler32.c -oadler32.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm zlib/trees.c -otrees.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm zlib/zutil.c -ozutil.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm zlib/deflate.c -odeflate.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm zlib/infblock.c -oinfblock.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm zlib/infcodes.c -oinfcodes.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm zlib/inffast.c -oinffast.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm zlib/inflate.c -oinflate.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm zlib/inftrees.c -oinftrees.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm zlib/infutil.c -oinfutil.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsapi.cpp -ojsapi.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsarena.cpp -ojsarena.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsbuiltins.cpp -ojsbuiltins.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsarray.cpp -ojsarray.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsatom.cpp -ojsatom.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsbool.cpp -ojsbool.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jscntxt.cpp -ojscntxt.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsdate.cpp -ojsdate.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsdbgapi.cpp -ojsdbgapi.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsdhash.cpp -ojsdhash.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsdtoa.cpp -ojsdtoa.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsemit.cpp -ojsemit.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsexn.cpp -ojsexn.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsfun.cpp -ojsfun.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jstracer.cpp -ojstracer.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsgc.cpp -ojsgc.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jshash.cpp -ojshash.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsinterp.cpp -ojsinterp.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsinvoke.cpp -ojsinvoke.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsiter.cpp -ojsiter.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jslock.cpp -ojslock.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jslog2.cpp -ojslog2.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsmath.cpp -ojsmath.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsnum.cpp -ojsnum.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsobj.cpp -ojsobj.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/json.cpp -ojson.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsopcode.cpp -ojsopcode.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsparse.cpp -ojsparse.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsprf.cpp -ojsprf.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsregexp.cpp -ojsregexp.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsscan.cpp -ojsscan.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsscope.cpp -ojsscope.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsscript.cpp -ojsscript.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsstr.cpp -ojsstr.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsutil.cpp -ojsutil.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsxdrapi.cpp -ojsxdrapi.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/jsxml.cpp -ojsxml.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/prmjtime.cpp -oprmjtime.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/nanojit/Assembler.cpp -onanojit_Assembler.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/nanojit/avmplus.cpp -onanojit_avmplus.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/nanojit/Fragmento.cpp -onanojit_Fragmento.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/nanojit/LIR.cpp -onanojit_LIR.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/nanojit/CodeAlloc.cpp -onanojit_CodeAlloc.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/nanojit/Containers.cpp -onanojit_Containers.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/nanojit/Allocator.cpp -onanojit_Allocator.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; EXPORT_JS_API; _declspec=__declspec; -I"c:\program files\bcc55\include;js/src/; js/;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm js/src/nanojit/RegAlloc.cpp -onanojit_RegAlloc.obj
bcc32.exe  -DFEATURE_NANOJIT; JS_TRACER; WIN32_LEAN_AND_MEAN=1; JS_HAVE_STDINT_H; NO_NOTES_MAIL; NO_CMC_MAIL; NO_DBF_ENCRYPTION; XP_WIN; winbcc; __winbcc__; SQLITE_OMIT_LOAD_EXTENSION; SQLITE_OMIT_AUTHORIZATION; SQLITE_OMIT_COMPLETE; SQLITE_OMIT_PROGRESS_CALLBACK; -I"c:\program files\bcc55\include;;." -nobj\ -5 -a4 -c -d -ff -H -Jgd -O1 -pr -Q -RT -WC -H=release.csm sqlite/sqlite3.c -osqlite3.obj
ilink32.exe  /L"c:\program files\bcc55\lib" /jobj\ /ap /c /q /Tpe /Gz C0X32 obj\jsdb.obj obj\wrap_sqlite.obj obj\wrap_process.obj obj\wrap_com.obj obj\wrap_debug.obj obj\wrap_env.obj obj\wrap_nums.obj obj\wrap_image.obj obj\wrap_index.obj obj\wrap_mail.obj obj\wrap_odbc.obj obj\wrap_record.obj obj\wrap_server.obj obj\wrap_shell.obj obj\wrap_system.obj obj\wrap_stream.obj obj\wrap_table.obj obj\wrap_zip.obj obj\dbf_cache.obj obj\dbf_dat.obj obj\dbf_file.obj obj\dbf_head.obj obj\dbf_io.obj obj\dbf_open.obj obj\dbf_rec.obj obj\gif_font.obj obj\gif_main.obj obj\io_b64.obj obj\io_comm.obj obj\io_compress.obj obj\io_expand.obj obj\io_file.obj obj\io_inet.obj obj\io_list.obj obj\io_memory.obj obj\io_fifo.obj obj\io_open.obj obj\io_pipe.obj obj\io_print.obj obj\io_stream.obj obj\io_xml.obj obj\io_zip.obj obj\ml_list.obj obj\ml_mapi.obj obj\ml_mapi2.obj obj\ml_mime.obj obj\ml_notes.obj obj\ml_open.obj obj\ml_pop.obj obj\ml_vim.obj obj\sy_alloc.obj obj\sy_char.obj obj\sy_crc.obj obj\sy_except.obj obj\sy_file.obj obj\sy_form.obj obj\sy_int32.obj obj\sy_list.obj obj\sy_mswin.obj obj\sy_param.obj obj\sy_sort.obj obj\sy_sql.obj obj\sy_string.obj obj\sy_strlist.obj obj\sy_time.obj obj\sy_url.obj obj\sy_worm.obj obj\tbl_asci.obj obj\tbl_cache.obj obj\tbl_data.obj obj\tbl_dbf.obj obj\tbl_index.obj obj\tbl_main.obj obj\tbl_sql.obj obj\adler32.obj obj\trees.obj obj\zutil.obj obj\deflate.obj obj\infblock.obj obj\infcodes.obj obj\inffast.obj obj\inflate.obj obj\inftrees.obj obj\infutil.obj obj\jsapi.obj obj\jsarena.obj obj\jsbuiltins.obj obj\jsarray.obj obj\jsatom.obj obj\jsbool.obj obj\jscntxt.obj obj\jsdate.obj obj\jsdbgapi.obj obj\jsdhash.obj obj\jsdtoa.obj obj\jsemit.obj obj\jsexn.obj obj\jsfun.obj obj\jstracer.obj obj\jsgc.obj obj\jshash.obj obj\jsinterp.obj obj\jsinvoke.obj obj\jsiter.obj obj\jslock.obj obj\jslog2.obj obj\jsmath.obj obj\jsnum.obj obj\jsobj.obj obj\json.obj obj\jsopcode.obj obj\jsparse.obj obj\jsprf.obj obj\jsregexp.obj obj\jsscan.obj obj\jsscope.obj obj\jsscript.obj obj\jsstr.obj obj\jsutil.obj obj\jsxdrapi.obj obj\jsxml.obj obj\prmjtime.obj obj\nanojit_Assembler.obj obj\nanojit_avmplus.obj obj\nanojit_Fragmento.obj obj\nanojit_LIR.obj obj\nanojit_CodeAlloc.obj obj\nanojit_Containers.obj obj\nanojit_Allocator.obj obj\nanojit_RegAlloc.obj obj\sqlite3.obj ,jsdb.exe,jsdb.map,IMPORT32 CW32MT,jsdb.def,obj\jsdb.res  
