g++ js/src/jskwgen.cpp -o jsdbconfig1.exe
jsdbconfig1.exe > js\jsautokw.h
g++ js/src/jscpucfg.cpp -o jsdbconfig2.exe
jsdbconfig2.exe > js\jsautocfg.h
g++ js/src/jsoplengen.cpp -o jsdbconfig3.exe
jsdbconfig3.exe js\jsautooplen.h
g++ jsdbconfigure.cpp -o jsdbconfig4.exe
jsdbconfig4.exe > js\js-config.h
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -idirafter rs/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsdb.o jsdb.cpp
windres.exe -o obj\jsdb.coff jsdb.rc 
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsapi.o js/src/jsapi.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsarena.o js/src/jsarena.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsbuiltins.o js/src/jsbuiltins.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsarray.o js/src/jsarray.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsatom.o js/src/jsatom.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsbool.o js/src/jsbool.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jscntxt.o js/src/jscntxt.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsdate.o js/src/jsdate.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsdbgapi.o js/src/jsdbgapi.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsdhash.o js/src/jsdhash.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsdtoa.o js/src/jsdtoa.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsemit.o js/src/jsemit.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsexn.o js/src/jsexn.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsfun.o js/src/jsfun.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jstracer.o js/src/jstracer.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsgc.o js/src/jsgc.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jshash.o js/src/jshash.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsinterp.o js/src/jsinterp.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsinvoke.o js/src/jsinvoke.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsiter.o js/src/jsiter.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jslock.o js/src/jslock.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jslog2.o js/src/jslog2.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsmath.o js/src/jsmath.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsnum.o js/src/jsnum.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsobj.o js/src/jsobj.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\json.o js/src/json.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsopcode.o js/src/jsopcode.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsparse.o js/src/jsparse.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsprf.o js/src/jsprf.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsregexp.o js/src/jsregexp.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsscan.o js/src/jsscan.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsscope.o js/src/jsscope.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsscript.o js/src/jsscript.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsstr.o js/src/jsstr.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsutil.o js/src/jsutil.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsxdrapi.o js/src/jsxdrapi.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\jsxml.o js/src/jsxml.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\prmjtime.o js/src/prmjtime.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\nanojit_Assembler.o js/src/nanojit/Assembler.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\nanojit_avmplus.o js/src/nanojit/avmplus.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\nanojit_Fragmento.o js/src/nanojit/Fragmento.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\nanojit_LIR.o js/src/nanojit/LIR.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\nanojit_CodeAlloc.o js/src/nanojit/CodeAlloc.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\nanojit_Containers.o js/src/nanojit/Containers.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\nanojit_Allocator.o js/src/nanojit/Allocator.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\nanojit_Nativei386.o js/src/nanojit/Nativei386.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D AVMPLUS_WIN32=1  -D AVMPLUS_IA32=1  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\nanojit_RegAlloc.o js/src/nanojit/RegAlloc.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_sqlite.o rs/wrap_sqlite.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_process.o rs/wrap_process.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_com.o rs/wrap_com.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_debug.o rs/wrap_debug.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_env.o rs/wrap_env.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_nums.o rs/wrap_nums.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_image.o rs/wrap_image.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_index.o rs/wrap_index.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_mail.o rs/wrap_mail.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_odbc.o rs/wrap_odbc.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_record.o rs/wrap_record.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_server.o rs/wrap_server.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_shell.o rs/wrap_shell.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_system.o rs/wrap_system.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_stream.o rs/wrap_stream.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_table.o rs/wrap_table.cpp
g++.exe  -c -fexceptions -I . -idirafter js/src/  -idirafter js/  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\wrap_zip.o rs/wrap_zip.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\dbf_cache.o rs/dbf_cache.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\dbf_dat.o rs/dbf_dat.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\dbf_file.o rs/dbf_file.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\dbf_head.o rs/dbf_head.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\dbf_io.o rs/dbf_io.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\dbf_open.o rs/dbf_open.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\dbf_rec.o rs/dbf_rec.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\gif_font.o rs/gif_font.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\gif_main.o rs/gif_main.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\io_b64.o rs/io_b64.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\io_comm.o rs/io_comm.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\io_compress.o rs/io_compress.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\io_expand.o rs/io_expand.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\io_file.o rs/io_file.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\io_inet.o rs/io_inet.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\io_list.o rs/io_list.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\io_memory.o rs/io_memory.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\io_fifo.o rs/io_fifo.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\io_open.o rs/io_open.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\io_pipe.o rs/io_pipe.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\io_print.o rs/io_print.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\io_stream.o rs/io_stream.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\io_xml.o rs/io_xml.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\io_zip.o rs/io_zip.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\ml_list.o rs/ml_list.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\ml_mapi.o rs/ml_mapi.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\ml_mapi2.o rs/ml_mapi2.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\ml_mime.o rs/ml_mime.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\ml_notes.o rs/ml_notes.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\ml_open.o rs/ml_open.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\ml_pop.o rs/ml_pop.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\ml_vim.o rs/ml_vim.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_alloc.o rs/sy_alloc.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_char.o rs/sy_char.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_crc.o rs/sy_crc.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_except.o rs/sy_except.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_file.o rs/sy_file.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_form.o rs/sy_form.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_int32.o rs/sy_int32.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_list.o rs/sy_list.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_mswin.o rs/sy_mswin.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_param.o rs/sy_param.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_sort.o rs/sy_sort.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_sql.o rs/sy_sql.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_string.o rs/sy_string.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_strlist.o rs/sy_strlist.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_time.o rs/sy_time.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_url.o rs/sy_url.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\sy_worm.o rs/sy_worm.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\tbl_asci.o rs/tbl_asci.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\tbl_cache.o rs/tbl_cache.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\tbl_data.o rs/tbl_data.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\tbl_dbf.o rs/tbl_dbf.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\tbl_index.o rs/tbl_index.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\tbl_main.o rs/tbl_main.cpp
g++.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -Wno-invalid-offsetof -Wno-conversion-null -O2 -Os  -oobj\tbl_sql.o rs/tbl_sql.cpp
gcc.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows   -O2 -Os  -oobj\adler32.o zlib/adler32.c
gcc.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows   -O2 -Os  -oobj\trees.o zlib/trees.c
gcc.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows   -O2 -Os  -oobj\zutil.o zlib/zutil.c
gcc.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows   -O2 -Os  -oobj\deflate.o zlib/deflate.c
gcc.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows   -O2 -Os  -oobj\infblock.o zlib/infblock.c
gcc.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows   -O2 -Os  -oobj\infcodes.o zlib/infcodes.c
gcc.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows   -O2 -Os  -oobj\inffast.o zlib/inffast.c
gcc.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows   -O2 -Os  -oobj\inflate.o zlib/inflate.c
gcc.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows   -O2 -Os  -oobj\inftrees.o zlib/inftrees.c
gcc.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows   -O2 -Os  -oobj\infutil.o zlib/infutil.c
gcc.exe  -c -fexceptions -I .  -D FEATURE_NANOJIT  -D JS_TRACER  -D WIN32_LEAN_AND_MEAN=1  -D JS_HAVE_STDINT_H  -D NO_NOTES_MAIL  -D NO_CMC_MAIL  -D NO_DBF_ENCRYPTION  -D XP_WIN  -D _Windows  -D SQLITE_OMIT_LOAD_EXTENSION  -D SQLITE_OMIT_AUTHORIZATION  -D SQLITE_OMIT_COMPLETE  -D SQLITE_OMIT_PROGRESS_CALLBACK   -O2 -Os  -oobj\sqlite3.o sqlite/sqlite3.c
gcc.exe  -static -s -o jsdb.exe -mconsole -mwindows -mole obj\jsdb.o obj\jsapi.o obj\jsarena.o obj\jsbuiltins.o obj\jsarray.o obj\jsatom.o obj\jsbool.o obj\jscntxt.o obj\jsdate.o obj\jsdbgapi.o obj\jsdhash.o obj\jsdtoa.o obj\jsemit.o obj\jsexn.o obj\jsfun.o obj\jstracer.o obj\jsgc.o obj\jshash.o obj\jsinterp.o obj\jsinvoke.o obj\jsiter.o obj\jslock.o obj\jslog2.o obj\jsmath.o obj\jsnum.o obj\jsobj.o obj\json.o obj\jsopcode.o obj\jsparse.o obj\jsprf.o obj\jsregexp.o obj\jsscan.o obj\jsscope.o obj\jsscript.o obj\jsstr.o obj\jsutil.o obj\jsxdrapi.o obj\jsxml.o obj\prmjtime.o obj\nanojit_Assembler.o obj\nanojit_avmplus.o obj\nanojit_Fragmento.o obj\nanojit_LIR.o obj\nanojit_CodeAlloc.o obj\nanojit_Containers.o obj\nanojit_Allocator.o obj\nanojit_Nativei386.o obj\nanojit_RegAlloc.o obj\wrap_sqlite.o obj\wrap_process.o obj\wrap_com.o obj\wrap_debug.o obj\wrap_env.o obj\wrap_nums.o obj\wrap_image.o obj\wrap_index.o obj\wrap_mail.o obj\wrap_odbc.o obj\wrap_record.o obj\wrap_server.o obj\wrap_shell.o obj\wrap_system.o obj\wrap_stream.o obj\wrap_table.o obj\wrap_zip.o obj\dbf_cache.o obj\dbf_dat.o obj\dbf_file.o obj\dbf_head.o obj\dbf_io.o obj\dbf_open.o obj\dbf_rec.o obj\gif_font.o obj\gif_main.o obj\io_b64.o obj\io_comm.o obj\io_compress.o obj\io_expand.o obj\io_file.o obj\io_inet.o obj\io_list.o obj\io_memory.o obj\io_fifo.o obj\io_open.o obj\io_pipe.o obj\io_print.o obj\io_stream.o obj\io_xml.o obj\io_zip.o obj\ml_list.o obj\ml_mapi.o obj\ml_mapi2.o obj\ml_mime.o obj\ml_notes.o obj\ml_open.o obj\ml_pop.o obj\ml_vim.o obj\sy_alloc.o obj\sy_char.o obj\sy_crc.o obj\sy_except.o obj\sy_file.o obj\sy_form.o obj\sy_int32.o obj\sy_list.o obj\sy_mswin.o obj\sy_param.o obj\sy_sort.o obj\sy_sql.o obj\sy_string.o obj\sy_strlist.o obj\sy_time.o obj\sy_url.o obj\sy_worm.o obj\tbl_asci.o obj\tbl_cache.o obj\tbl_data.o obj\tbl_dbf.o obj\tbl_index.o obj\tbl_main.o obj\tbl_sql.o obj\adler32.o obj\trees.o obj\zutil.o obj\deflate.o obj\infblock.o obj\infcodes.o obj\inffast.o obj\inflate.o obj\inftrees.o obj\infutil.o obj\sqlite3.o  obj\jsdb.coff  -lole32  -lws2_32  -lstdc++  -lodbc32  -loleaut32  -lmapi32  -lcomdlg32  -luuid  -lwinmm   
